###################  mybatis-plus配置  ###################
mybatis-plus:
#  mapper-locations: classpath*:com/iciyun/adi/microframe/order/**/xml/*.xml
#  typeAliasesPackage: com.iciyun.adi.microframe.order.persistence.entity
#  global-config:
#    id-type: 3  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#debug: true

